base_url = "https://semanticdata.github.io/zola-resume"
title = "Zola Resume"
description = "A simple resume for Zola."
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false
